defaultPortal: dev_project1
portals:
  - name: dev_project1
    portalId: 45278553
    env: prod
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CMKhkY7bMRIRAA0AQAAA4C0DQAJYAgEAAMgY2crLFSCi98geKO7pDDIUNw44lGn3wTXmNzi_LSKYegiQ-gU6QQAABEEAAAB4AAAAAAAAAAAAgAAAAAAABAAAwAcAjvAxPGAQBgBEAGBA_BgGABAgAwAAAAAAPAIDAAAAAAAAAAwEQhQVyNK3AL3faYfTKhpnI0Tb7KemvUoDbmExUgBaAA
        expiresAt: '2024-02-16T11:54:09.495Z'
    accountType: STANDARD
    personalAccessKey: >-
      CiQyNGZkOGU3NS1mMDYyLTRkNTItODYwMy0xN2NjNzZmMzVkMDUQ2crLFRii98geKhkABeaRgvmemGtF6JCFy-sLoF_rDCi76HTBSgNuYTE
    sandboxAccountType: null
