defaultPortal: dev_project1
portals:
  - name: dev_project1
    portalId: 45278553
    env: prod
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CK6iq43bMRIRAA0AQAAA4C0DQAJYAgEAAMgY2crLFSCi98geKO7pDDIUdgKj8ZMFHGEyMwv0FQ7hXAEW_w46QQAABEEAAAB4AAAAAAAAAAAAgAAAAAAABAAAwAcAjvAxPGAQBgBEAGBA_BgGABAgAwAAAAAAPAIDAAAAAAAAAAwEQhShOjTZluZ--yvXjQGJY81XfNF3xkoDbmExUgBaAA
        expiresAt: '2024-02-16T11:26:18.435Z'
    accountType: STANDARD
    personalAccessKey: >-
      CiQyNGZkOGU3NS1mMDYyLTRkNTItODYwMy0xN2NjNzZmMzVkMDUQ2crLFRii98geKhkABeaRgvmemGtF6JCFy-sLoF_rDCi76HTBSgNuYTE
    sandboxAccountType: null
